version: '3.2'
services:
  e2e:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run cy:run
    volumes:
      - ./cypress/videos:/app/cypress/videos
      - ./cypress/screenshots:/app/cypress/screenshots
    working_dir: /app